mkdir 1-Iterator
mkdir 2-Adapter
mkdir 3-TemplateMethod
mkdir 4-FactoryMethod
mkdir 5-Singleton
mkdir 6-Prototype
mkdir 7-Builder
mkdir 8-AbstractFactory
mkdir 9-Bridge
mkdir 10-Strategy
mkdir 11-Compsite
mkdir 12-Decorator
mkdir 13-Visitor
mkdir 14-ChainOfResponsibility
mkdir 15-Facade
mkdir 16-Mediator
mkdir 17-Observer
mkdir 18-Memento
mkdir 19-Strate 
mkdir 20-Flyweight
mkdir 21-Proxy
