@startuml Strategyパターン

package Strategyパターン <<Rectangle>> {
    class Report {
        + Formatter formatter
        + void initialize(Formatter formatter)
        + void print_output()
    }

    abstract class Formatter {
        + {abstract} void do_format(String title, String body)
    }

    class HTMLFormatter {
        + void do_format(String title, String body)
    }

    class PlainTextFormatter {
        + void do_format(String title, String body)
    }
}

Report *- Formatter : call >
Formatter <|-- HTMLFormatter : extends
Formatter <|-- PlainTextFormatter : extends

@enduml
